### ISSUE TITLE
Permission to Point some people to my Repo - EXPERIMENTAL

### ISSUE THREAD

**Issue by cryptonomicon314** [ckald/pyccoon#14]
I added support for both Haskell and Clojure (Clojurescript support comes for free with Clojure, because they are almost identical), as well as support for automatically defined anchors in the source code.

I'd like to break backward compatibility in some places, and share my changes with actual Clojure programmers (I'm learning clojure in my free time) to see what they think. Would you mind if I pointed those people to my version while these changes are ready to merge into version 1.0?

The main features I added was support for automatic anchors to sections in which functions are defined. For example, sourcecode

``` clojure
(defn foo [bar]
  (...))
```

Adds the invisible anchor to the text part of the section

``` html
<a id="code.foo"></a>
```

So that you can refer to this function definition using the markdown extension `[|foo @ filename-where-foo-is-defined|]` or `[|foo|]` if  `foo` is defined in the current file.

It is not very good to generate links to methods in a Python class, because it will generate repeated anchors if there are different classes with the same methods. I'll have to change it to go back to the parent section where the class name is defined.

The feature I would like to add is automatically hyperlinked source (with a decent amount of help by the user)

**Comment by ckald** [comment]
I was thinking about this feature. Personally, I'd prefer the combination of syntax of Markdown links we already use `[[anchor|path/to/the/file#section]]` and Sublime Text's goto-anything: `path/to/the/file@function` or `path/to/the/file:linenumber`.

So my preferred syntax will look like:
- `[[path/to/the/file@function]]` 
- `[[anchor|path/to/the/file@function]]`

This does not require any new constructs, just another branch in `replace_crossref` function.

Because of the problem you mentioned, it is evident that we need a simplest algorithm for parsing a source file into a tree. That might be quite complicated to implement manually, but I'm pretty sure that we could reuse the modules used by the editors for autocompletion and go-to-definition features. I remember installing one massive library of this kind, but unfortunately I can't find it right away.

If we find that library, we can also use it's database to add lots of languages because it will definitely contain information about scope-defining statements.

Regarding the permission: of course you've got it, we are open source. And you can create a PR for your changes if you think they're ready

**Comment by ckald** [comment]
Might be useful (but not what I am looking for): https://pypi.python.org/pypi/CodeIntel

**Comment by ckald** [comment]
Here it is: http://ctags.sourceforge.net/ . It is tool that parses the source code an creates an index of objects. Does not support neither Haskell nor Clojure, but there's a workaround for the latter: http://clojurewise.blogspot.com/2010/03/using-ctags-with-clojure.html

Another interesting thingy: http://cedet.sourceforge.net/intellisense.shtml

**Comment by cryptonomicon314** [comment]
I've broken backward compatibility, but I guess it's worth it.
I've turned .pyccoon into .pyccoon.yaml, as we had discussed.

I've added support for hyperlinks in clojure files (not in my repo yet). It works using (dead-stupid) syntatic analysis only, but it works surprisingly well. The trick is to turn (perhaps qualified) names into urls that point either to local files or to external websites. Currently I support links to this website: https://crossclj.info/. This requires the user to define a mapping between module names and package names, but I include a big default map so that more common packages are supported out of the box.

The user can specify the mapping between namespaces and packages in the .pyccoon.yaml file, like this:

``` yaml
project:
    name: re-frame 0.4.1

files:
    # Note that we don't need to escape '\' in the strings:
    skip:
        - docs.*
        - \.git.*
        - .*/resources/public/js.*
    copy: []

documentation:
    css-path: null
    custom-html-template: null
    mathjax: true # should I make this the default? probably not...
    linebreaking-behavior: normal # this is now the default

language-specific:
    clojure:
        namespaces:
            # Local namespaces
            re-frame:
                # this method links to local files
                method: local
                # Relative to the directory on which
                # `pyccoon` is called.
                path: src/re_frame
                extension: cljs

            reagent.core:
                # this method links to the crosscljs.info website
                method: crossclj
                package: reagent
                is-cljs: true
                source: true
```

(actually, you don't need to mention reagent.core here, because it is included in the default mapping)

I had to turn .pyccoon into .pyccoon.yaml because otherwise the configuration would become unreadable. I'll document these options and try to implement equivalent functionality for python.

I'll upload my example project (a fork of the clojurescript re-frame library) so you can see what my version is capable of.
